examenT1_POO1_Rosas_Chinen_Raul_Ichiro/POO1_T1_Rosas_Chinen_Raul_Ichiro/Controllers/CoordinadorController.cs
using Microsoft.AspNetCore.Mvc;
using POO1_T1_Regalado_Quispe_Mateo.Models;

namespace POO1_T1_Regalado_Quispe_Mateo.Controllers
{
    public class CoordinadorController : Controller
    {
        public IActionResult Index()
        {
            List<CoordinadorEnt> listaCoordinador = new CoordinadorDto().ListarCoordinador();
            return View(listaCoordinador);
        }

        public IActionResult Create()
        {
            CoordinadorEnt ent = new CoordinadorEnt();
            return View(ent);
        }

        [HttpPost]

        public ActionResult Create(CoordinadorEnt ent)
        {
            if (string.IsNullOrWhiteSpace(ent.Nombres))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo nombre es Obligatorio";
                return View(ent);
            }
            if (string.IsNullOrWhiteSpace(ent.Apellidos))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo Apellidos es Obligatorio";
                return View(ent);
            }
            if (string.IsNullOrWhiteSpace(ent.NroDocumento))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo NroDocumento es Obligatorio";
                return View(ent);
            }
            if (ent.FechaNacimiento.Year == 1)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese una fecha de Nacimiento correcta";
                return View(ent);
            }
            if (ent.FechaContrato.Year == 1)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese una fecha de Contrato correcta";
                return View(ent);
            }

            if (ent.HorasTrabajadas <= 0)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese Correctamente las horas trabajadas";
                return View(ent);
            }

            if (ent.Tarifa <= 0)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese Correctamente la Tarifa";
                return View(ent);
            }

            if (ent.AniosServicio <= 0)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese Correctamente los Años de servicio";
                return View(ent);
            }

            if (ent.Titulado != 0 && ent.Titulado != 1)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese Correctamente el Titulado (Solo acepta 1 y 0)";
                return View(ent);
            }

            string mensaje = new CoordinadorDto().RegistrarCoordinador(ent);
            ViewBag.Mensaje = mensaje;
            return View(ent);
        }
    }
}

examenT1_POO1_Rosas_Chinen_Raul_Ichiro/POO1_T1_Rosas_Chinen_Raul_Ichiro/Controllers/TrabajadorController.cs
using Microsoft.AspNetCore.Mvc;
using POO1_T1_Regalado_Quispe_Mateo.Models;

namespace POO1_T1_Regalado_Quispe_Mateo.Controllers
{
    public class TrabajadorController : Controller
    {
        public IActionResult Index()
        {
            List<TrabajadorEnt> listaTrabajador = new TrabajadorDto().ListarTrabajador();
            return View(listaTrabajador);
        }

        public IActionResult Create()
        {
            TrabajadorEnt ent = new TrabajadorEnt();    
            return View(ent);   
        }

        [HttpPost]

        public ActionResult Create(TrabajadorEnt ent)
        {
            if(string.IsNullOrWhiteSpace(ent.Nombres))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo nombre es Obligatorio";
                return View(ent);
            }
            if (string.IsNullOrWhiteSpace(ent.Apellidos))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo Apellidos es Obligatorio";
                return View(ent);
            }
            if (string.IsNullOrWhiteSpace(ent.NroDocumento))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo NroDocumento es Obligatorio";
                return View(ent);
            }
            if (ent.FechaNacimiento.Year == 1)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese una fecha de Nacimiento correcta";
                return View(ent);
            }
            if (ent.FechaContrato.Year == 1)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese una fecha de Contrato correcta";
                return View(ent);
            }

            if(ent.HorasTrabajadas <= 0)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese Correctamente las horas trabajadas";
                return View(ent);
            }

            if (ent.Tarifa <= 0)
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "Ingrese Correctamente la Tarifa";
                return View(ent);
            }

            string mensaje = new TrabajadorDto().RegistrarTrabajador(ent);
            ViewBag.Mensaje = mensaje;  
            return View(ent);   
        }
    }
}

examenT1_POO1_Rosas_Chinen_Raul_Ichiro/POO1_T1_Rosas_Chinen_Raul_Ichiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - POO1_T1_Rosas_Chinen_Raul_Ichiro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/POO1_T1_Rosas_Chinen_Raul_Ichiro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">POO1_T1_Rosas_Chinen_Raul_Ichiro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trabajador" asp-action="Index">Trabajador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coordinador" asp-action="Index">Coordinador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - POO1_T1_Rosas_Chinen_Raul_Ichiro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>