clases/MiproyectoWEb/Models/DocenteEnt.cs
namespace MiproyectoWEb.Models
{
    public class DocenteEnt : PersonaEnt
    {
        public int TiempoServicio { get; set; }
        public int TipoServicio { get; set; }  //1 = parcial , 2= completo

        public override  double Bonificacion() {
            double _bonificacion = 150;
            double _bono1 = 0;
            double _bono2 = 0;

            if (TiempoServicio > 4) {
                _bono1 = _bonificacion * 0.30;
            }
            if (TipoServicio == 2) {
                _bono2 = _bonificacion * 0.15;
            }

            _bonificacion = _bonificacion + _bono1 + _bono2;
            return _bonificacion;
        }
    }
}

clases/MiproyectoWEb/Models/DocentoDto.cs
namespace MiproyectoWEb.Models
{
    public class DocentoDto
    {
        static List<DocenteEnt> objListaDocente = new List<DocenteEnt>();
        static int _IdPersona = 0;

        public List<DocenteEnt> ListaDocente()
        {
            return objListaDocente;
        }

        public string RegistrarDocente(DocenteEnt objDocente)
        {
            _IdPersona++;
            objDocente.IdPersona = _IdPersona;
            objListaDocente.Add(objDocente);
            return "Se ha registrado a: " + objDocente.Nombres;
        }
    }
}

clases/MiproyectoWEb/Models/ErrorViewModel.cs
namespace MiproyectoWEb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

clases/MiproyectoWEb/Models/PersonaDto.cs
namespace MiproyectoWEb.Models
{
    public class PersonaDto
    {
        static List<PersonaEnt> objListaPersona = new List<PersonaEnt>();
        static int _IdPersona = 0;

        public List<PersonaEnt> ListaPersona() { 
            return objListaPersona;
        }

        public string RegistrarPersona(PersonaEnt objPersona) { 
            _IdPersona++;
            objPersona.IdPersona = _IdPersona;
            objListaPersona.Add(objPersona);
            return "Se ha registrado a: " + objPersona.Nombres;
        }
    }
}

clases/MiproyectoWEb/Models/PersonaEnt.cs
namespace MiproyectoWEb.Models
{
    public class PersonaEnt
    {
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public double sueldo { get; set; }

        public int CalcularEdad() 
        { 
            int _edad = DateTime.Now.Year - FechaNacimiento.Year;
            return _edad;
        }

        public virtual double Bonificacion() {
            return 150;
        }

        public double SueldoTotal() {
            double _sueldo = sueldo + Bonificacion();
            return _sueldo;
        }

    }
}

clases/MiproyectoWEb/Controllers/DocenteController.cs
using Microsoft.AspNetCore.Mvc;
using MiproyectoWEb.Models;

namespace MiproyectoWEb.Controllers
{
    public class DocenteController : Controller
    {
        public IActionResult Index()
        {
            List<DocenteEnt> Lista = new DocentoDto().ListaDocente();
            return View(Lista);
        }

        public IActionResult Create()
        {
            DocenteEnt ent = new DocenteEnt();
            return View(ent);
        }
        [HttpPost]
        public ActionResult Create(DocenteEnt ent)
        {
            if (string.IsNullOrWhiteSpace(ent.Nombres))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo Nombre es obligatorio!";
                return View(ent);
            }

            String Mensaje = new DocentoDto().RegistrarDocente(ent);
            ViewBag.Mensaje = Mensaje;
            return View(ent);
        }
    }
}

clases/MiproyectoWEb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MiproyectoWEb.Models;
using System.Diagnostics;

namespace MiproyectoWEb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

clases/MiproyectoWEb/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using MiproyectoWEb.Models;

namespace MiproyectoWEb.Controllers
{
    public class PersonaController : Controller
    {
        public IActionResult Index()
        {
            List<PersonaEnt> Lista = new PersonaDto().ListaPersona();
            return View(Lista);
        }

        public IActionResult Create()
        { 
            PersonaEnt ent = new PersonaEnt();
            return View(ent);
        }
        [HttpPost]
        public ActionResult Create(PersonaEnt ent)
        { 
            if(string.IsNullOrWhiteSpace(ent.Nombres))
            {
                ViewBag.Mensaje = "";
                ViewBag.MensajeError = "El campo Nombre es obligatorio!";
                return View(ent);
            }



            String Mensaje = new PersonaDto().RegistrarPersona(ent);
            ViewBag.Mensaje = Mensaje;
            return View(ent);
        }
    }
}

clases/MiproyectoWEb/Views/Docente/Create.cshtml
@model DocenteEnt

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (!string.IsNullOrWhiteSpace(ViewBag.Mensaje))
{
    @ViewBag.Mensaje

}

@if (!string.IsNullOrWhiteSpace(ViewBag.MensajeError))
{
    @ViewBag.MensajeError

}

<form asp-action="Create" asp-controller="Docente" method="post">
    <div class="row">
        <div class="col-md-2">
            Nombre
            @Html.TextBoxFor(x => x.Nombres)
        </div>
        <div class="col-md-2">
            Fecha Nacimiento
            @Html.TextBoxFor(x => x.FechaNacimiento, "{0:dd/MM/yyyy}", new { type = "date" })
        </div>
        <div class="col-md-2">
            Sueldo
            @Html.TextBoxFor(x => x.sueldo)
        </div>
        <div class="col-md-2">
            Tiempo de Servicio
            @Html.TextBoxFor(x => x.TiempoServicio)
        </div>
        <div class="col-md-2">
            Tipo de Servicio
            @Html.TextBoxFor(x => x.TipoServicio)
        </div>
        <div class="col-md-2">
            <button class="btn btn-success"> Agregar </button>
        </div>
    </div>
</form>

clases/MiproyectoWEb/Views/Docente/Index.cshtml
@model IEnumerable<DocenteEnt>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id Docente</th>
                <th>Nombres</th>
                <th>FechaNacimiento</th>
                <th>Edad</th>
                <th>sueldo</th>
                <th>Bonificacion</th>
                <th>Sueldo total</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.IdPersona</td>
                        <td>@item.Nombres</td>
                        <td>@item.FechaNacimiento</td>
                        <td>@item.CalcularEdad()</td>
                        <td>@item.sueldo</td>
                        <td>@item.Bonificacion()</td>
                        <td>@item.SueldoTotal()</td>
                    </tr>
                }
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7">Total Registros: @Model.Count()</td>
            </tr>
        </tfoot>
    </table>
</div>

<div class="row">
    <a href='@Url.Action("Create","Docente")' class="btn btn-primary btn-lg">Registrar Nuevo Docente</a>
</div>

clases/MiproyectoWEb/Views/Persona/Create.cshtml
@model PersonaEnt 

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (!string.IsNullOrWhiteSpace(ViewBag.Mensaje))
{
    @ViewBag.Mensaje

}

@if (!string.IsNullOrWhiteSpace(ViewBag.MensajeError))
{
    @ViewBag.MensajeError

}

<form asp-action="Create" asp-controller="Persona" method="post">
    <div class="row">
        <div class="col-md-2">
            Nombre
            @Html.TextBoxFor(x => x.Nombres)
        </div>
        <div class="col-md-2">
            Fecha Nacimiento
            @Html.TextBoxFor(x => x.FechaNacimiento, "{0:dd/MM/yyyy}", new { type = "date" })
        </div>
        <div class="col-md-2">
            Sueldo
            @Html.TextBoxFor(x => x.sueldo)
        </div>
        <div class="col-md-2">
            <button class="btn btn-success"> Agregar </button>
        </div>
    </div>
</form>

clases/MiproyectoWEb/Views/Persona/Index.cshtml
@model IEnumerable<PersonaEnt>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id Persona</th>
                <th>Nombres</th>
                <th>FechaNacimiento</th>
                <th>Edad</th>
                <th>sueldo</th>
                <th>Bonificacion</th>
                <th>Sueldo total</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                @foreach (var item in Model)
                {                    
                    <tr>
                        <td>@item.IdPersona</td>
                        <td>@item.Nombres</td>
                        <td>@item.FechaNacimiento</td>
                        <td>@item.CalcularEdad()</td>
                        <td>@item.sueldo</td>
                        <td>@item.Bonificacion()</td>
                        <td>@item.SueldoTotal()</td>
                    </tr>
                }

            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="7">Total Registros: @Model.Count()</td>
            </tr>
        </tfoot>
    </table>
</div>

<div class="row">
    <a href='@Url.Action("Create","Persona")' class="btn btn-primary btn-lg">Registrar Nueva Persona</a>
</div>

clases/MiproyectoWEb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiproyectoWEb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiproyectoWEb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiproyectoWEb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persona" asp-action="Index">Persona</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Docente" asp-action="Index">Docente</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MiproyectoWEb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>